### ISSUE TITLE
ShouldBindJSON修改为ShouldBind兼容json和form表单

### ISSUE THREAD

**Issue by dongshanlang** [axetroy/go-server#121]
func SignInRouter(c *gin.Context) {
	var (
		input SignInParams
		err   error
		res   = schema.Response{}
	)

	defer func() {
		if err != nil {
			res.Data = nil
			res.Message = err.Error()
		}
		c.JSON(http.StatusOK, res)
	}()
	**if err = c.ShouldBindJSON(&input);** err != nil {
		err = exception.InvalidParams
		return
	}

	res = SignIn(controller.NewContext(c), input)
}
在学习您的代码，ShouldBindJSON改为ShouldBind可以兼容前端json和form，会不会好一些

**Comment by axetroy** [comment]
我是坚定的 json 派，form 和 xml 那种什么的老古董，不会支持的[手动狗头]

**Comment by dongshanlang** [comment]
哦哦，明白
