### ISSUE TITLE
gin与iris选择

### ISSUE THREAD

**Issue by dongshanlang** [axetroy/go-server#314]
hello， why use iris instead of gin? what's the difference?

**Comment by axetroy** [comment]
gin 的 Api 命名比较规范统一，iris 的有一些混乱

但是就一个很简单的原因就让我放弃了 gin

gin 基于 fasthttp，丑陋的路由满足不了需求

**Comment by dongshanlang** [comment]
哦哦，原来是这样，感谢回答。
