### ISSUE TITLE
手机注册的参数

### ISSUE THREAD

**Issue by BenDaye** [axetroy/go-server#316]
现在手机注册时不需要填密码,注册成功后,就没法用密码登录.

1. 保持现在的注册逻辑,修改密码可使用code && new_password,接口判断code || old_password
2. 改注册的参数为code&phone&password&invite_code

可能用1比较好,吧？

**Comment by axetroy** [comment]
这一点确实是疏忽了，现在修改密码只能是用 `old_password` 去修改

我觉得该用方案 2

因为方案 1 的时候，前端不太好判断到底是传 `old_password` 还是 `code`

那么在注册的时候，就可选得填入 `password`, 如果不填，那么就走【忘记密码】的流程

**Comment by axetroy** [comment]
今晚更
