### ISSUE TITLE
抽象 httpserver，剥离对 gin 的依赖

### ISSUE THREAD

**Issue by axetroy** [axetroy/go-server#53]
目前有好多地方用到 gin 的依赖

接下来就是剥离对 gin 的依赖，抽象化 http 服务

这样使得我在切换 http 框架的时候，可以做到很低的成本切换。

`gin` 框架确实向换了

**Comment by chenhui7373** [comment]
I think goframe is your best choice for instead of.Plz consider my suggestion.
